### ISSUE TITLE
Install issue keeps happening no matter how I install

### ISSUE THREAD

**Issue by eglxiang** [arraiyopensource/torchgeometry#99]
import torchgeometry
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "torchgeometry/__init__.py", line 3, in <module>
    from torchgeometry import core
  File "torchgeometry/core/__init__.py", line 1, in <module>
    from .homography_warper import HomographyWarper, homography_warp
  File "torchgeometry/core/homography_warper.py", line 39
    height: int,
          ^

**Comment by eglxiang** [comment]
This is common issue as there's another friend who finds this problem as well. It seems to be caused by torch version... only torch 1.0 supported?
Could the developer give some quick pointer here? Much appreciated!

**Comment by eglxiang** [comment]
Or deos this library only work for Python3?
sorry for keep asking...

**Comment by Merical** [comment]
@eglxiang I think it may be a python version issue. Python 3.5 does not support this variable annotation.

**Comment by edgarriba** [comment]
@eglxiang you are probably using python < v3.6. The typing sintax we support is for >= v3.6. As for pytorch, we support >= v1.0.0. Let us know if you solve the issue with this.

**Comment by eglxiang** [comment]
I see. But I need to call this library for my existing repository that relies on Py2.7. Will Py 2.7 be supported in the near future?

**Comment by edgarriba** [comment]
Supporting 2.7 could be such a pain right know basically because most of the code relies on typing and that means rewriting a lot of things to support typing for 2.7 which has a totally different syntax. Another reason is that python 2.7 will be deprecated in less than a year. See https://pythonclock.org 

We can disscuss more about this so that you can use torchgeometry but what about upgrading your repo to python3? Unless you don't have a lot of prints in your code, it should be pretty straightforward.

Is it public your report?

**Comment by edgarriba** [comment]
@eglxiang we added the requirement to the package setup in https://github.com/arraiyopensource/torchgeometry/pull/104.
Closing this.
